# Generated by Django 3.2.25 on 2024-07-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_rename_service_orderdetail_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='package',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
