# Generated by Django 3.2.25 on 2024-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='کد تخفیف')),
                ('amount', models.IntegerField(verbose_name='درصد تخفیف')),
                ('expire_date', models.CharField(help_text='توجه: موعد انقضای کد تخفیف فیلد مربوطه توسط ادمین حذف شود', max_length=200, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
