# Generated by Django 3.2.25 on 2024-08-01 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_module', '0006_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
