# Generated by Django 3.2.25 on 2024-08-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_module', '0007_discountcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='user',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='account_module.myuser', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
