# Generated by Django 3.2.25 on 2024-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0008_auto_20240801_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_order_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی محصولات داخل سبد خرید'),
        ),
    ]
