# Generated by Django 3.2.25 on 2024-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_order_final_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='کد رهگیری'),
        ),
    ]
