# Generated by Django 3.2.25 on 2024-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_orderdetail_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_used',
            field=models.BooleanField(default=False, help_text='بعد از مراجعه کاربر به پذیرش و تایید پرداختی ایشان ، این فیلد باید تیک خورده تا از استفاده مجدد این پکیج منع گردد.', verbose_name='استفاده شده / نشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(help_text='حتی اگر کد رهگیری کاربر با مطالعات شما مطابقت داشت ولی سبد خرید ایشان نهایی نشده بود، فرد را از ادامه ی فرایند ثبت نام منع کنید. این رویداد هرگز رخ نخواهد داد مگر اینکه شخص مراجعه کننده برنامه نویس و هکر باشد و قصد سو استفاده داشته باشد.', verbose_name='نهایی شده / نشده'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='در بررسی کد رهگیری کاربر دقت به عمل آورید.', max_length=8, null=True, verbose_name='کد رهگیری'),
        ),
    ]
