# Generated by Django 3.2.25 on 2024-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0013_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='is_used',
            field=models.BooleanField(default=False, help_text='بعد از مراجعه کاربر به پذیرش و تایید کد رهگیری ایشان ، این فیلد باید تیک خورده تا از استفاده مجدد این پکیج منع گردد.', verbose_name='استفاده شده / نشده'),
        ),
    ]
