# Generated by Django 3.2.25 on 2024-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0016_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, help_text='در بررسی کد رهگیری کاربر دقت به عمل آورید.', max_length=8, null=True, verbose_name='کد رهگیری'),
        ),
    ]
