# Generated by Django 3.2.25 on 2024-07-11 03:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroducingTheServicesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons', verbose_name='آیکن')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'توضیحات یک آیتم خدمات',
                'verbose_name_plural': 'باکس های توضیحات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orange_title', models.CharField(default='منتظر حضور گرمتان هستیم', max_length=150, verbose_name='عنوان طلایی رنگ')),
                ('black_title', models.CharField(default='باشگاه تشریفاتی آریا', max_length=150, verbose_name='عنوان مشکی رنگ')),
                ('image_one', models.ImageField(upload_to='services/building', verbose_name='تصویر اول از نمای مجموعه')),
                ('image_two', models.ImageField(upload_to='services/building', verbose_name='تصویر دوم از نمای مجموعه')),
                ('short_description', models.CharField(max_length=400, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('imp_description', models.CharField(max_length=400, verbose_name='توضیحات مهم')),
            ],
            options={
                'verbose_name': 'توضیحات آموزشی',
                'verbose_name_plural': 'توضیحات اموزشی خرید از سایت',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('english_name', models.CharField(default='swimming pool', max_length=300, verbose_name='عنوان خدمات به انگلیسی')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('short_description_main_page', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه در صفحه اصلی')),
                ('image_header', models.ImageField(upload_to='services/header_images', verbose_name='تصویر هدر')),
                ('title_img_header', models.CharField(max_length=40, verbose_name='عنوان روی تصویر هدر')),
                ('short_description_of_img_header', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات کوتاه روی تصویر هدر')),
                ('introduce_title', models.CharField(blank=True, default='معرفی خدمات ما', max_length=50, null=True, verbose_name='عنوان بخش توضیحات')),
                ('discount_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان نمایشی تخفیف')),
                ('discount_number', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='فعال / غیرفعال')),
                ('purchase_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='services_module.purchasemethod', verbose_name='نحوه خرید از وب سایت')),
            ],
            options={
                'verbose_name': 'آیتم خدمات',
                'verbose_name_plural': 'خدمات مجموعه',
            },
        ),
        migrations.CreateModel(
            name='TablePricesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان جدول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_price_box', to='services_module.services', verbose_name='دسته خدمات')),
            ],
            options={
                'verbose_name': 'عنوان جدول',
                'verbose_name_plural': 'عنوان جداول',
            },
        ),
        migrations.CreateModel(
            name='TablePricesRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=300, verbose_name='نام پکیج')),
                ('package_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پکیج')),
                ('price', models.IntegerField(verbose_name='قیمت (تومان)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_prices_rows', to='services_module.tablepricesbox', verbose_name='دسته جدول')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج ها و قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='ServicesSliderBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گالری تصاویر', max_length=30, verbose_name='عنوان باکس اسلایدر')),
                ('background_img', models.ImageField(upload_to='services/slider', verbose_name='تصویر پس زمینه باکس اسلایدر')),
                ('category_services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='svc_slider_box', to='services_module.services', verbose_name='دسته خدمات')),
            ],
            options={
                'verbose_name': 'باکس اسلایدر',
                'verbose_name_plural': 'باکس های اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='ServicesSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slider', models.ImageField(upload_to='services/slider', verbose_name='تصویر اسلایدر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svc_slider', to='services_module.servicessliderbox', verbose_name='دسته باکس اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='ServicesItemsBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='امکانات بخش استخر', max_length=70, verbose_name='عنوان بخش امکانات')),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='services/icons', verbose_name='آیکن بخش امکانات')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items_box', to='services_module.services', verbose_name='دسته خدمات')),
            ],
            options={
                'verbose_name': 'باکس امکانات',
                'verbose_name_plural': 'باکس های امکانات',
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(max_length=30, verbose_name='عنوان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services_module.servicesitemsbox', verbose_name='دسته بخش امکانات')),
            ],
            options={
                'verbose_name': 'آیتم امکانات',
                'verbose_name_plural': 'امکانات خدمات',
            },
        ),
        migrations.CreateModel(
            name='MoreDetailsIntroducing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('introducing_services_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_detail_introduce', to='services_module.introducingtheservicesbox', verbose_name='دسته توضیحات')),
            ],
            options={
                'verbose_name': 'توضیحات بیشتر یک آیتم خدمات',
                'verbose_name_plural': 'توضیحات بیشتر خدمات',
            },
        ),
        migrations.AddField(
            model_name='introducingtheservicesbox',
            name='services_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduce_svc_box', to='services_module.services', verbose_name='دسته خدمات'),
        ),
    ]
