# Generated by Django 3.2.25 on 2024-07-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='work_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image_header',
            field=models.ImageField(upload_to='services/header_images', verbose_name='تصویر اصلی'),
        ),
    ]
