# Generated by Django 3.2.25 on 2024-07-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0002_auto_20240716_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image_header',
            new_name='main_img',
        ),
    ]
