# Generated by Django 3.2.25 on 2024-07-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0003_rename_image_header_services_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='short_description_of_img_header',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه روی تصویر هدر'),
        ),
    ]
