# Generated by Django 3.2.25 on 2024-07-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0004_alter_services_short_description_of_img_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='services',
            name='short_description_main_page',
        ),
        migrations.RemoveField(
            model_name='services',
            name='work_time',
        ),
        migrations.AddField(
            model_name='services',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='services/header_images', verbose_name='تصویر هدر'),
        ),
    ]
