# Generated by Django 3.2.25 on 2024-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0005_auto_20240716_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepricesbox',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='عنوان جدول'),
        ),
    ]
