# Generated by Django 3.2.25 on 2024-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0006_alter_tablepricesbox_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
