# Generated by Django 3.2.25 on 2024-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0008_alter_services_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepricesrows',
            name='discount_price',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
