# Generated by Django 3.2.25 on 2024-07-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0009_tablepricesrows_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='date_created',
        ),
    ]
