# Generated by Django 3.2.25 on 2024-08-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0012_alter_tablepricesrows_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='meta_description',
            field=models.CharField(blank=True, help_text='برای افزایش سئو یک متن 160 کاراکتری ، ترغیب کننده ، جذاب و مرتبط با محتوای قرار گرفته در این صفحه بنویسید.', max_length=160, null=True, verbose_name='متاتگ برای سئو'),
        ),
    ]
