# Generated by Django 3.2.25 on 2024-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0013_services_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='keyword_eight',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی هشتم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_five',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی پنجم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_four',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی چهارم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_nine',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی نهم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_one',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی اول'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_seven',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی هفتم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_six',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی ششم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_ten',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی دهم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_three',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی سوم'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_two',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی دوم'),
        ),
    ]
