# Generated by Django 3.2.25 on 2024-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0015_auto_20240807_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='english_name',
            field=models.CharField(default='swimming pool', help_text='برای عنوان خدمات این صفحه از ترکیب یک یا چند کلمه انگلیسی استفاده کنید مانند مثال داخل فیلد که برای عنوان خدمات استخر در نظر گرفته شده.', max_length=300, verbose_name='عنوان خدمات به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='ترجیحا در این فیلد تغییر ایجاد نکنید و این فیلد متناسب با نام انگلیسی در نظر گرفته شده در فیلد قبلی به صورت خودکار تولید می شود.', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(help_text='عنوان خدمات را بنویسید', max_length=40, verbose_name='عنوان'),
        ),
    ]
