# Generated by Django 3.2.25 on 2024-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0016_auto_20240807_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='header_img',
            field=models.ImageField(upload_to='services/header_images', verbose_name='تصویر هدر'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='', help_text='ترجیحا در این فیلد تغییر ایجاد نکنید و این فیلد متناسب با نام انگلیسی در نظر گرفته شده در فیلد قبلی به صورت خودکار تولید می شود.', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
    ]
