# Generated by Django 3.2.25 on 2024-08-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0017_auto_20240809_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='introduce_title',
            field=models.CharField(default='معرفی خدمات ما', max_length=50, verbose_name='عنوان بخش توضیحات'),
        ),
    ]
