# Generated by Django 3.2.25 on 2024-08-28 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0018_alter_services_introduce_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepricesrows',
            name='discount_number',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='tablepricesrows',
            name='discount_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان نمایشی تخفیف'),
        ),
    ]
