# Generated by Django 3.2.25 on 2024-08-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0019_auto_20240828_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='discount_number',
        ),
    ]
