# Generated by Django 3.2.25 on 2024-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0021_services_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepricesrows',
            name='order',
            field=models.IntegerField(default=1, help_text='برای هر خدمات یک اولیت بر اساس عدد تایین کنید تا به ترتیب اولیت شما در وب سایت دیده شود', verbose_name='اولویت بر اساس عدد'),
            preserve_default=False,
        ),
    ]
