# Generated by Django 3.2.25 on 2024-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('site_logo', models.ImageField(upload_to='site-setting/logo', verbose_name='لوگوی سایت')),
                ('slogan_one', models.CharField(max_length=200, verbose_name='شعار مشکی رنگ')),
                ('slogan_two', models.CharField(max_length=200, verbose_name='شعار طلایی رنک')),
                ('phone', models.CharField(max_length=25, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('working_time', models.TextField(verbose_name='ساعات کاری')),
                ('about_des', models.TextField(verbose_name='توضیحات کوتاه معرفی سایت')),
                ('location_link', models.URLField(verbose_name='لوکیشن')),
                ('whatsapp_link', models.URLField(verbose_name='واتس آپ')),
                ('telegram_link', models.URLField(verbose_name='تلگرام')),
                ('youtube_link', models.URLField(verbose_name='یوتیوب')),
                ('instagram_link', models.URLField(verbose_name='اینستاگرام')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت')),
                ('developer', models.CharField(max_length=200, verbose_name='متن معرفی طراح و توسعه دهنده')),
                ('footer_img', models.ImageField(upload_to='site-setting/footer-images', verbose_name='تصویر پس زمینه فوتر')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
