# Generated by Django 3.2.25 on 2024-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_link',
            field=models.URLField(verbose_name=' لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='location_link',
            field=models.URLField(verbose_name='لینک لوکیشن'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram_link',
            field=models.URLField(verbose_name=' لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_link',
            field=models.URLField(verbose_name='لینک واتس آپ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='working_time',
            field=models.CharField(max_length=200, verbose_name='ساعات کاری'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_link',
            field=models.URLField(verbose_name=' لینک یوتیوب'),
        ),
    ]
