# Generated by Django 3.2.25 on 2024-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_auto_20240714_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='تلفن'),
        ),
    ]
