# Generated by Django 3.2.25 on 2024-07-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitesetting_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_header',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن با کدشهر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_notif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن بدون پیش شماره'),
        ),
    ]
