# Generated by Django 3.2.25 on 2024-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_auto_20240714_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_header',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن با کد شهر'),
        ),
    ]
