# Generated by Django 3.2.25 on 2024-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_auto_20240714_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آی دی اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آی دی تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره واتس آپ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_link',
            field=models.URLField(verbose_name='لینک یوتیوب'),
        ),
    ]
