# Generated by Django 3.2.25 on 2024-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20240714_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enamad_img',
            field=models.ImageField(blank=True, null=True, upload_to='site-setting/footer-images', verbose_name='تصویر ای نماد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='samandehi_img',
            field=models.ImageField(blank=True, null=True, upload_to='site-setting/footer-images', verbose_name='تصویر ساماندهی'),
        ),
    ]
