# Generated by Django 3.2.25 on 2024-07-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_auto_20240714_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='enamad_img',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='samandehi_img',
        ),
    ]
