# Generated by Django 3.2.25 on 2024-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_auto_20240714_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('desktop_img', models.ImageField(upload_to='site-setting/home-slider', verbose_name='تصویر اسلایدر در ابعاد دسکتاپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر های اصلی',
            },
        ),
        migrations.CreateModel(
            name='TitleDescriptionHomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'عنوان و توضیحات اسلایدر',
                'verbose_name_plural': 'عنوان و توضیحات اسلایدر',
            },
        ),
    ]
