# Generated by Django 3.2.25 on 2024-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0010_homeslider_titledescriptionhomeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledescriptionhomeslider',
            name='meta_description',
            field=models.CharField(blank=True, help_text='برای افزایش سئو یک متن 160 کاراکتری ، ترغیب کننده ، جذاب و مرتبط با محتوای قرار گرفته در صفحه اصلی سایت بنویسید.', max_length=160, null=True, verbose_name='متاتگ برای سئو'),
        ),
        migrations.AlterField(
            model_name='titledescriptionhomeslider',
            name='description',
            field=models.TextField(help_text='توضیحات کوتاه روی اسلایدر اصلی در صفحه اصلی', verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='titledescriptionhomeslider',
            name='title',
            field=models.CharField(help_text='عنوان روی اسلایدر اصلی در صفحه اصلی', max_length=300, verbose_name='عنوان'),
        ),
    ]
