# Generated by Django 3.2.25 on 2024-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_auto_20240807_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='is_main_setting',
            field=models.BooleanField(help_text='فقط مجاز هستید یک تنظیمات اصلی داشته باشید.', verbose_name='تنظیمات اصلی'),
        ),
    ]
