# Generated by Django 3.2.25 on 2024-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0012_alter_sitesetting_is_main_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enamad_img',
            field=models.ImageField(blank=True, help_text='اختیاری', null=True, upload_to='site-setting/footer-images', verbose_name='تصویر ای نماد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='samandehi_img',
            field=models.ImageField(blank=True, help_text='اختیاری', null=True, upload_to='site-setting/footer-images', verbose_name='تصویر سامان دهی'),
        ),
    ]
