# Generated by Django 3.2.25 on 2024-08-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_auto_20240808_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enamad_url',
            field=models.URLField(blank=True, help_text='اختیاری', null=True, verbose_name='لینک ای نماد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='samandehi_url',
            field=models.URLField(blank=True, help_text='اختیاری', null=True, verbose_name='لینک ساماندهی'),
        ),
    ]
