# Generated by Django 3.2.25 on 2024-08-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0014_auto_20240808_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(max_length=100, verbose_name='آی دی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_header',
            field=models.CharField(max_length=50, verbose_name='تلفن با کد شهر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_notif',
            field=models.CharField(max_length=50, verbose_name='تلفن بدون پیش شماره'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(default=False, max_length=100, verbose_name='آی دی تلگرام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(default=True, max_length=100, verbose_name='شماره واتس آپ'),
            preserve_default=False,
        ),
    ]
