# Generated by Django 3.2.25 on 2024-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_auto_20240809_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='desktop_img',
            field=models.ImageField(upload_to='site-setting/home-slider', verbose_name='تصویر اسلایدر'),
        ),
    ]
