# Generated by Django 3.2.25 on 2024-08-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0016_alter_homeslider_desktop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledescriptionhomeslider',
            name='is_active',
            field=models.BooleanField(help_text='فقط یک عنوان و توضیحات روی اسلایدر صفحه اصلی سایت مجاز می باشد.', verbose_name='فعال / غیرفعال'),
        ),
    ]
