# Generated by Django 3.2.25 on 2024-07-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=40, verbose_name='عنوان هدر')),
                ('header_img', models.ImageField(upload_to='services/header_images', verbose_name='تصویر هدر')),
                ('header_phone_title', models.CharField(max_length=200, verbose_name='عنوان جدول شماره تماس ها')),
                ('building_img_one', models.ImageField(upload_to='site-setting/home-slider', verbose_name='تصویر کوچک اول')),
                ('building_img_two', models.ImageField(upload_to='site-setting/home-slider', verbose_name='تصویر کوچک دوم')),
                ('title_sm_img_one', models.CharField(max_length=200, verbose_name='متن کوتاه تبلیغاتی اول')),
                ('title_sm_img_two', models.CharField(max_length=200, verbose_name='متن کوتاه تبلیغاتی دوم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('addr_link', models.URLField(verbose_name='لینک آدرس گوگل مپ')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات صفحه تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='PhoneTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_part', models.CharField(max_length=150, verbose_name='بخش')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('setting_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_table', to='contact_module.contactussetting', verbose_name='دسته تنظیمات')),
            ],
            options={
                'verbose_name': 'شماره بخش',
                'verbose_name_plural': 'شماره تماس بخش های مجموعه',
            },
        ),
    ]
