# Generated by Django 3.2.25 on 2024-07-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_contactussetting_phonetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactussetting',
            name='addr_link',
            field=models.TextField(verbose_name='لینک آدرس گوگل مپ'),
        ),
    ]
