# Generated by Django 3.2.25 on 2024-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_alter_contactussetting_addr_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactussetting',
            options={},
        ),
        migrations.AddField(
            model_name='contactussetting',
            name='keyword_one',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی اول'),
        ),
        migrations.AddField(
            model_name='contactussetting',
            name='keyword_three',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی سوم'),
        ),
        migrations.AddField(
            model_name='contactussetting',
            name='keyword_two',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی دوم'),
        ),
        migrations.AddField(
            model_name='contactussetting',
            name='meta_description',
            field=models.CharField(blank=True, help_text='برای افزایش سئو یک متن 160 کاراکتری ، ترغیب کننده ، جذاب و مرتبط با محتوای قرار گرفته در این صفحه بنویسید.', max_length=160, null=True, verbose_name='متاتگ برای سئو'),
        ),
        migrations.AlterField(
            model_name='contactussetting',
            name='is_main_setting',
            field=models.BooleanField(default=False, help_text='فقط یک تنظیمات اصلی برای صفحه تماس با ما مجاز هستید داشته باشید', verbose_name='تنظیمات اصلی'),
        ),
    ]
