# Generated by Django 3.2.25 on 2024-08-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_auto_20240807_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactussetting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات صفحه تماس با ما'},
        ),
    ]
