# Generated by Django 3.2.25 on 2024-07-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0005_auto_20240716_0400'),
        ('home_module', '0002_homeservices_svc_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='svc_cat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services_module.services', verbose_name='دسته بندی'),
        ),
    ]
