# Generated by Django 3.2.25 on 2024-07-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=20, verbose_name='عنوان هدر')),
                ('header_short_description', models.TextField(verbose_name='توضیحات کوتاه هدر')),
                ('header_img', models.ImageField(upload_to='about-us/images', verbose_name='تصویر هدر')),
                ('video_title', models.CharField(max_length=200, verbose_name='عنوان ویدیو معرفی')),
                ('video_link', models.URLField(verbose_name='لینک ویدیو')),
                ('title_managers_records', models.CharField(max_length=100, verbose_name='عنوان باکس سوابق مدیران')),
                ('logo', models.ImageField(upload_to='about-us/images', verbose_name='تصویر لوگو')),
                ('description_one', models.TextField(verbose_name='توضیحات اول')),
                ('description_two', models.TextField(verbose_name='توضیحات دوم')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه درباره ما',
                'verbose_name_plural': 'تنظیمات درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('profile_img', models.ImageField(upload_to='about-us/images', verbose_name='عکس پروفایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('about_page_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='about_module.aboutus', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مدیر',
                'verbose_name_plural': 'مدیران',
            },
        ),
    ]
