# Generated by Django 3.2.25 on 2024-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='is_main_setting',
            field=models.BooleanField(default=False, help_text='توجه: فقط یک تنظیات اصلی مجاز است', verbose_name='تنظیمات اصلی'),
        ),
    ]
