# Generated by Django 3.2.25 on 2024-07-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0002_alter_aboutus_is_main_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='سمت'),
        ),
    ]
