# Generated by Django 3.2.25 on 2024-07-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0003_managers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
