# Generated by Django 3.2.25 on 2024-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0004_alter_managers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title_managers_records',
            field=models.CharField(max_length=200, verbose_name='عنوان باکس سوابق مدیران'),
        ),
    ]
