# Generated by Django 3.2.25 on 2024-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0005_alter_aboutus_title_managers_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='keyword_one',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی اول'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keyword_three',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی سوم'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keyword_two',
            field=models.CharField(blank=True, help_text='یک کلمه کلیدی برای افزایش رتبه گوگل یا سئو ، متناسب با محتوای این صفحه بنویسید', max_length=160, null=True, verbose_name='کلمه کلیدی دوم'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='meta_description',
            field=models.CharField(blank=True, help_text='برای افزایش سئو یک متن 160 کاراکتری ، ترغیب کننده ، جذاب و مرتبط با محتوای قرار گرفته در این صفحه بنویسید.', max_length=160, null=True, verbose_name='متاتگ برای سئو'),
        ),
    ]
