# Generated by Django 3.2.25 on 2024-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0006_auto_20240807_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='description',
            field=models.TextField(blank=True, help_text='اختیاری', null=True, verbose_name='توضیحات'),
        ),
    ]
