# Generated by Django 3.2.25 on 2024-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0008_alter_managers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title_managers_records',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان باکس سوابق مدیران'),
        ),
    ]
