# Generated by Django 3.2.25 on 2024-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_myuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کاربری'),
        ),
    ]
