# Generated by Django 3.2.25 on 2024-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, default='aria', max_length=200, null=True, verbose_name='نام کاربری'),
        ),
    ]
