# Generated by Django 3.2.25 on 2024-07-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
