# Generated by Django 3.2.25 on 2024-07-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
