# Generated by Django 3.2.25 on 2024-08-05 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_messagebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGroupKavehNegar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='عنوان پیام صرفا برای نمایش مشخصه ای از پیام در لیست پیام های گروهی کاربرد دارد', max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'لیست پیام های گروهی با پنل پیامکی',
            },
        ),
    ]
