# Generated by Django 3.2.25 on 2024-08-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0016_messagegroupkavehnegar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageGroupKavehNegar',
        ),
    ]
