# Generated by Django 3.2.25 on 2024-08-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0018_messagegroupkavehnegar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagegroupkavehnegar',
            name='user',
        ),
    ]
