# Generated by Django 3.2.25 on 2024-08-06 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0020_auto_20240806_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='mobile',
            field=models.CharField(default=False, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
