# Generated by Django 3.2.25 on 2024-08-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0021_auto_20240806_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='mobile',
        ),
    ]
