# Generated by Django 3.2.25 on 2024-08-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0022_remove_loginattempt_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_failed_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
